name: deploy
on:
  push:
    branches:
      - master
jobs:
  connect:
    runs-on: ubuntu-latest
    env:
      SSH_USER: "root"
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Pull the updates
        run: ssh staging '
          export PATH=$PATH:/root/.nvm/versions/node/v14.16.1/bin &&
          export NODE_ENV=production &&
          cd ~/reaction-frontend &&
          git checkout master &&
          git pull &&
          npm install &&
          npm run build &&
          npm run serve'
